package simulator.view;

import java.awt.Color;
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import simulator.control.Automaton;
import simulator.control.RegularGrammar;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    JFileChooser jfc;
    File file;
    File fileGrammar;
    
    List<String> list;
    Automaton automaton;
    RegularGrammar rg;
    
    Automaton automaton2;
    RegularGrammar rg2;
    List<String> list2;
            
    public Main() {
        initComponents();
        jfc = new JFileChooser();
        jfc.setFileFilter(new FileNameExtensionFilter("txt", "txt", "text"));
        
        this.btnVerify.setEnabled(false);
        this.btnVerify.setEnabled(false);
        this.fldSentence.setEditable(false);
        this.fldSentence.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAutomaton = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblGrammar = new javax.swing.JLabel();
        panelAutomatonFile = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        fldFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVerify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fldSentence = new javax.swing.JTextArea();
        lblSentence = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblStepByStep = new javax.swing.JLabel();
        panelGrammar = new javax.swing.JPanel();
        panelAutomatonFile1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        fldFile1 = new javax.swing.JTextField();
        btnFile1 = new javax.swing.JButton();
        lblMsg1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblGrammar1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lblAFN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador Universal de AFD");
        setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Gramática Regular")));

        jScrollPane2.setViewportView(lblGrammar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAutomatonFile.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblTitle.setText("Simulador Universal de Autômato Finito Determinístico");

        fldFile.setEditable(false);
        fldFile.setText("Nenhum autômato selecionado");
        fldFile.setEnabled(false);
        fldFile.setFocusable(false);
        fldFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldFileActionPerformed(evt);
            }
        });

        btnFile.setText("Selecionar Arquivo");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAutomatonFileLayout = new javax.swing.GroupLayout(panelAutomatonFile);
        panelAutomatonFile.setLayout(panelAutomatonFileLayout);
        panelAutomatonFileLayout.setHorizontalGroup(
            panelAutomatonFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAutomatonFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAutomatonFileLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAutomatonFileLayout.createSequentialGroup()
                        .addComponent(fldFile, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFile, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAutomatonFileLayout.setVerticalGroup(
            panelAutomatonFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAutomatonFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Verificar Sentença"));

        btnVerify.setText("Verificar");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        fldSentence.setColumns(20);
        fldSentence.setLineWrap(true);
        fldSentence.setRows(5);
        jScrollPane1.setViewportView(fldSentence);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerify, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addComponent(lblSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerify, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Etapas de Leitura"));

        jScrollPane3.setViewportView(lblStepByStep);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAutomatonLayout = new javax.swing.GroupLayout(panelAutomaton);
        panelAutomaton.setLayout(panelAutomatonLayout);
        panelAutomatonLayout.setHorizontalGroup(
            panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonLayout.createSequentialGroup()
                .addGroup(panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAutomatonFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAutomatonLayout.setVerticalGroup(
            panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAutomatonFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAutomatonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autômato", panelAutomaton);

        panelAutomatonFile1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTitle1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblTitle1.setText("Conversor de Gramática Regular em AFN");

        fldFile1.setEditable(false);
        fldFile1.setText("Nenhuma gramática selecionada");
        fldFile1.setEnabled(false);
        fldFile1.setFocusable(false);
        fldFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldFile1ActionPerformed(evt);
            }
        });

        btnFile1.setText("Selecionar Arquivo");
        btnFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAutomatonFile1Layout = new javax.swing.GroupLayout(panelAutomatonFile1);
        panelAutomatonFile1.setLayout(panelAutomatonFile1Layout);
        panelAutomatonFile1Layout.setHorizontalGroup(
            panelAutomatonFile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonFile1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAutomatonFile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAutomatonFile1Layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAutomatonFile1Layout.createSequentialGroup()
                        .addComponent(fldFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFile1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAutomatonFile1Layout.setVerticalGroup(
            panelAutomatonFile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutomatonFile1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAutomatonFile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Gramática Regular")));

        jScrollPane4.setViewportView(lblGrammar1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("AFN"));

        jScrollPane5.setViewportView(lblAFN);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGrammarLayout = new javax.swing.GroupLayout(panelGrammar);
        panelGrammar.setLayout(panelGrammarLayout);
        panelGrammarLayout.setHorizontalGroup(
            panelGrammarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrammarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrammarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAutomatonFile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGrammarLayout.setVerticalGroup(
            panelGrammarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrammarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrammarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrammarLayout.createSequentialGroup()
                        .addComponent(panelAutomatonFile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Gramática", panelGrammar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Autômato");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        // TODO add your handling code here:
        
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            fldFile.setText(file.getName());
            
            this.setComponentsActiveState(true);
            
            list = new ArrayList<>();
            
            try {
                FileReader fr = new FileReader(file.getAbsolutePath());
                BufferedReader bf = new BufferedReader(fr);
                
                String line = bf.readLine();
                while(line != null && !line.isEmpty()) {
                    list.add(line);
                    line = bf.readLine();
                }
                
                automaton = new Automaton(list);
                
                if(!automaton.validateDFA()) {
                    this.setComponentsActiveState(false);
                    this.lblMsg.setText("O autômato não é AFD!");
                    this.lblMsg.setForeground(Color.red);
                    
                    this.lblGrammar.setText("");
                }else {
                    this.lblMsg.setText("O autômato é AFD!");
                    this.lblMsg.setForeground(new Color(0, 153, 0));
                    
                    rg = new RegularGrammar(automaton);
                    this.lblGrammar.setText(rg.getGrammar());
                }
                
            } catch (FileNotFoundException e) {
                this.setComponentsActiveState(false);
                this.lblMsg.setText("Arquivo não encontrado!");
                this.lblMsg.setForeground(Color.red);
            } catch (IOException e) {
                System.out.println(e.toString());
            }
        }
        
    }//GEN-LAST:event_btnFileActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
            // TODO add your handling code here:
            
            if(automaton.verifySentence(fldSentence.getText())) {
                this.lblSentence.setText("A sentença é válida!");
                this.lblSentence.setForeground(new Color(0, 153, 0));
            } else {
                this.lblSentence.setText("A sentença não é válida!");
                this.lblSentence.setForeground(Color.red);
            }
            
            this.lblStepByStep.setText(automaton.getReading());
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void fldFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldFileActionPerformed

    private void fldFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldFile1ActionPerformed

    private void btnFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile1ActionPerformed
        // TODO add your handling code here:
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fileGrammar = jfc.getSelectedFile();
            fldFile1.setText(fileGrammar.getName());
            
            this.setComponentsActiveState(true);
            
            list2 = new ArrayList<>();
            
            try {
                FileReader fr = new FileReader(fileGrammar.getAbsolutePath());
                BufferedReader bf = new BufferedReader(fr);
                
                String line = bf.readLine();
                while(line != null && !line.isEmpty()) {
                    list2.add(line);
                    line = bf.readLine();
                }
                
                rg2 = new RegularGrammar(list2);
                
                this.lblAFN.setText(rg2.toAutomatonString());
                this.lblGrammar1.setText(rg2.getGrammar());
                
                /*
                if(!automaton.validateDFA()) {
                    this.setComponentsActiveState(false);
                    this.lblMsg.setText("O autômato não é AFD!");
                    this.lblMsg.setForeground(Color.red);
                    
                    this.lblGrammar.setText("");
                }else {
                    this.lblMsg.setText("O autômato é AFD!");
                    this.lblMsg.setForeground(new Color(0, 153, 0));
                    
                    rg = new RegularGrammar(automaton);
                    this.lblGrammar.setText(rg.getGrammar());
                }
                */
                
            } catch (FileNotFoundException e) {
                this.setComponentsActiveState(false);
                this.lblMsg1.setText("Arquivo não encontrado!");
                this.lblMsg1.setForeground(Color.red);
            } catch (IOException e) {
                System.out.println(e.toString());
            }
        }
        
    }//GEN-LAST:event_btnFile1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Main main = new Main();
            main.setLocationRelativeTo(null);
            main.setVisible(true);
        });
    }
    
    private void setComponentsActiveState(boolean bool) {
        this.btnVerify.setEnabled(bool);
        this.btnVerify.setEnabled(bool);
        this.fldSentence.setEditable(bool);
        this.fldSentence.setEnabled(bool);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnFile1;
    private javax.swing.JButton btnVerify;
    private javax.swing.JTextField fldFile;
    private javax.swing.JTextField fldFile1;
    private javax.swing.JTextArea fldSentence;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAFN;
    private javax.swing.JLabel lblGrammar;
    private javax.swing.JLabel lblGrammar1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblMsg1;
    private javax.swing.JLabel lblSentence;
    private javax.swing.JLabel lblStepByStep;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel panelAutomaton;
    private javax.swing.JPanel panelAutomatonFile;
    private javax.swing.JPanel panelAutomatonFile1;
    private javax.swing.JPanel panelGrammar;
    // End of variables declaration//GEN-END:variables
}